<?php

namespace Helix\Site;

use Helix\Site;
use Throwable;

/**
 * @var View $this
 * @var Site $site
 * @var Throwable $error
 */

$response = $site->getResponse();
$code = $response->getCode();

if ($error instanceof HttpError) {
    $message = $error->getMessage();
} elseif ($site->isDev()) {
    $message = "[{$error->getCode()}] $error";
} else {
    $message = 'Internal Server Error';
}
?>
<html lang="en">
<head>
    <title><?= $code ?></title>
</head>
<body>
<h1><?= $code ?></h1>
<pre><?= $message ?></pre>
<?php
if ($code >= 500): ?>
    <pre>Reference #<?= $response->getId() ?></pre>
<?php
endif ?>
</body>
</html>
